---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-0
  namespace: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "sharedfast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-1
  namespace: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "sharedfast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datadir-kafka-2
  namespace: kafka
  annotations:
    volume.beta.kubernetes.io/storage-class: "sharedfast"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi